packages:
  - .
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@ai-sdk/openai@4.0.8'
  - ai@7.0.16
  - '@expo/cli@57.0.6'
  - '@expo/config-plugins@57.0.3'
  - '@expo/config@57.0.3'
  - '@expo/fingerprint@0.20.3'
  - '@expo/inline-modules@0.1.2'
  - '@expo/prebuild-config@57.0.5'
  - '@expo/router-server@57.0.2'
  - babel-preset-expo@57.0.2
  - expo-modules-autolinking@57.0.5
  - expo-modules-core@57.0.3
  - expo-modules-jsi@57.0.1
  - expo@57.0.4
onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - sharp
  - workerd
